In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
import os

In [2]:
os.chdir('dataset')
!dir

 Volume in drive C has no label.
 Volume Serial Number is 9A3C-60F9

 Directory of C:\Users\wali\Documents\Projects\RegressionModels\dataset

06/15/2024  06:47 PM    <DIR>          .
06/17/2024  09:28 PM    <DIR>          ..
05/02/2024  01:01 PM           280,246 BTC-USD.csv
06/15/2024  06:47 PM            26,717 CarPrice.csv
05/02/2024  12:59 PM               109 COMPLETE_FLIGHT_DATASET_2015.txt
05/02/2024  12:57 PM         1,500,835 Dry_Bean.csv
05/02/2024  12:57 PM           342,976 FLIGHT-2015.csv
06/07/2024  09:58 PM         2,296,273 FLIGHT100k.csv
06/15/2024  06:37 PM           107,745 infrared_thermography_temperature.csv
05/02/2024  12:57 PM            48,136 NHANES_age_prediction.csv
05/17/2024  02:40 PM           430,835 Rice_Cammeo_Osmancik.csv
06/15/2024  06:40 PM           131,539 SalesData.csv
              10 File(s)      5,165,411 bytes
               2 Dir(s)  72,052,912,128 bytes free


In [3]:
df = pd.read_csv('BTC-USD.csv')
df.head()

Date        Open        High         Low       Close   Adj Close  \
0  9/17/2014  465.864014  468.174011  452.421997  457.334015  457.334015   
1  9/18/2014  456.859985  456.859985  413.104004  424.440002  424.440002   
2  9/19/2014  424.102997  427.834991  384.532013  394.795990  394.795990   
3  9/20/2014  394.673004  423.295990  389.882996  408.903992  408.903992   
4  9/21/2014  408.084991  412.425995  393.181000  398.821014  398.821014   

       Volume  
0  21056800.0  
1  34483200.0  
2  37919700.0  
3  36863600.0  
4  26580100.0

In [4]:
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

In [19]:
df

Open          High           Low         Close  \
Date                                                                 
2014-09-17    465.864014    468.174011    452.421997    457.334015   
2014-09-18    456.859985    456.859985    413.104004    424.440002   
2014-09-19    424.102997    427.834991    384.532013    394.795990   
2014-09-20    394.673004    423.295990    389.882996    408.903992   
2014-09-21    408.084991    412.425995    393.181000    398.821014   
...                  ...           ...           ...           ...   
2024-04-23  66839.890630  67199.242190  65864.867190  66407.273440   
2024-04-24  66408.718750  67075.367190  63589.871090  64276.898440   
2024-04-25  64275.019530  65275.207030  62783.632810  64481.707030   
2024-04-26  64485.371090  64789.656250  63322.398440  63755.320310   
2024-04-27  63753.121090  63885.769530  62581.515630  62839.320310   

               Adj Close        Volume  
Date                                    
2014-09-17    457.334015  2.105680e+07  
2014-09-18    424.440002  3.448320e+07  
2014-09-19    394.795990  3.791970e+07  
2014-09-20    408.903992  3.686360e+07  
2014-09-21    398.821014  2.658010e+07  
...                  ...           ...  
2024-04-23  66407.273440  2.431098e+10  
2024-04-24  64276.898440  3.027666e+10  
2024-04-25  64481.707030  3.215579e+10  
2024-04-26  63755.320310  2.413937e+10  
2024-04-27  62839.320310  1.916508e+10  

[3511 rows x 6 columns]

In [7]:
features = df[['Open', 'High', 'Low', 'Volume']]
target = df['Close']

In [8]:
scaler = MinMaxScaler()
features_scaled = scaler.fit_transform(features)

In [9]:
features_scaled

array([[3.96374745e-03, 3.48720151e-03, 3.94746772e-03, 4.31449169e-05],
       [3.84023959e-03, 3.33334944e-03, 3.39495837e-03, 8.14009011e-05],
       [3.39091346e-03, 2.93865744e-03, 2.99345536e-03, 9.11925571e-05],
       ...,
       [8.79231053e-01, 8.84755852e-01, 8.79846115e-01, 9.16049727e-02],
       [8.82116436e-01, 8.78153163e-01, 8.87417026e-01, 6.87637194e-02],
       [8.72072196e-01, 8.65861796e-01, 8.77005898e-01, 5.45904007e-02]])

In [11]:
X_train, X_test, y_train, y_test = train_test_split(features_scaled, target, test_size=0.2, random_state=42)

In [12]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [13]:
predict = model.predict(X_test)
mse = mean_squared_error(y_test, predict)
print('Mean Squared Error:' ,mse)

Mean Squared Error: 86298.58298079633


In [14]:
r2 = r2_score(y_test,predict)
print('R2 Score',r2)

R2 Score 0.9996968623487388


In [20]:
model.predict([[8.72072196e-01, 8.65861796e-01, 8.77005898e-01, 5.45904007e-02]])

array([62903.1301418])

In [81]:
import numpy as np
def predict(o,h,l,v):
#     ope = float(input("Enter the Open value: "))
#     high = float(input("Enter the High value: "))
#     low = float(input("Enter the Low value: "))
#     vol = float(input("Enter the Volume value: "))
    f = [[o,h,l,v]]
    print(type(f))
    print(f)
#     f = [ope,high,low,vol]
#     f.reshape(-1,1)
    print(type(f))
    print(f)
    scaled = scaler.fit_transform(f)
#     scaled.reshape(1,-1)
    print(scaled)
    result = model.predict(scaled)
    print("Result",result)

In [82]:
predict(465,468,452,23456789)

<class 'list'>
[[465, 468, 452, 23456789]]
<class 'list'>
[[465, 468, 452, 23456789]]
[[0. 0. 0. 0.]]
Result [204.25377727]
